// Auth
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
// locations
export const SELECTED_LOCATION_UPDATE = "SELECTED_LOCATION_UPDATE";
export const GET_LOCATIONS_SUCCESS = "GET_LOCATIONS_SUCCESS";
export const GET_LOCATIONS_FAILURE = "GET_LOCATIONS_FAILURE";
export const ADD_LOCATION_SUCCESS = "ADD_LOCATION_SUCCESS";
export const ADD_LOCATION_FAILURE = "ADD_LOCATION_FAILURE";
export const UPDATE_LOCATION_SUCCESS = "UPDATE_LOCATION_SUCCESS";
export const UPDATE_LOCATION_FAILURE = "UPDATE_LOCATION_FAILURE";
export const DELETE_LOCATION_SUCCESS = "DELETE_LOCATION_SUCCESS";
export const DELETE_LOCATION_FAILURE = "DELETE_LOCATION_FAILURE";
// Permit
export const UPDATE_VEHICLE_REGISTER_FORM_DATA =
  "UPDATE_VEHICLE_REGISTER_FORM_DATA";
export const SUBMIT_PERMIT_SUCCESS = "SUBMIT_PERMIT_SUCCESS";
export const SUBMIT_PERMIT_FAIL = "SUBMIT_PERMIT_FAIL";
export const GET_PERMITS_SUCCESS = "GET_PERMITS_SUCCESS";
export const GET_PERMITS_FAILURE = "GET_PERMITS_FAILURE";
export const DELETE_PERMIT_SUCCESS = "DELETE_PERMIT_SUCCESS";
export const DELETE_PERMIT_FAILURE = "DELETE_PERMIT_FAILURE";
export const UPDATE_PERMIT_FAILURE = "UPDATE_PERMIT_FAILURE";
export const UPDATE_PERMIT_SUCCESS = "UPDATE_PERMIT_SUCCESS";
export const GET_USERS_PERMITS_SUCCESS = "GET_USERS_PERMITS_SUCCESS";
export const GET_USERS_PERMITS_FAILURE = "GET_USERS_PERMITS_FAILURE";
// user
export const UPDATE_CURRENT_USER_SUCCESS = "UPDATE_CURRENT_USER_SUCCESS";
export const UPDATE_CURRENT_USER_FAILURE = "UPDATE_CURRENT_USER_FAILURE";
export const UPDATE_CURRENT_USER_PASSWORD_SUCCESS =
  "  UPDATE_CURRENT_USER_PASSWORD_SUCCESS";
export const UPDATE_CURRENT_USER_PASSWORD_FAILURE =
  "  UPDATE_CURRENT_USER_PASSWORD_FAILURE";
